46_urlmanager/basic/controllers/MemberController.php
<?php
namespace app\controllers;
use app\controllers\CommonController;
use app\models\User;
use Yii;

class MemberController extends CommonController
{

    protected $except = ['auth', 'logout', 'reg', 'qqreg', 'qqlogin', 'qqcallback'];

    public function actionAuth()
    {
        $this->layout = 'layout2';
        if (Yii::$app->request->isGet) {
            $url = Yii::$app->request->referrer;
            if (empty($url)) {
                $url = "/";
            }
            Yii::$app->session->setFlash('referrer', $url);
        }
        $model = new User;
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if ($model->login($post)) {
                $url = Yii::$app->session->getFlash('referrer');
                return $this->redirect($url);
            }
        }
        return $this->render("auth", ['model' => $model]);
    }

    public function actionLogout()
    {   
        /*Yii::$app->session->remove('loginname');
        Yii::$app->session->remove('isLogin');
        if (!isset(Yii::$app->session['isLogin'])) {
            return $this->goBack(Yii::$app->request->referrer);
        }*/
        Yii::$app->user->logout(false);
        return $this->goBack(Yii::$app->request->referrer);
    }

    public function actionReg()
    {
        $model = new User;
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if ($model->regByMail($post)) {
                Yii::$app->session->setFlash('info', '电子邮件发送成功');
            }
        }
        $this->layout = 'layout2';
        return $this->render('auth', ['model' => $model]);
    }

    public function actionQqlogin()
    {
        require_once("../vendor/qqlogin/qqConnectAPI.php");
        $qc = new \QC();
        $qc->qq_login();
    }

    public function actionQqcallback()
    {
        require_once("../vendor/qqlogin/qqConnectAPI.php");
        $auth = new \OAuth();
        $accessToken = $auth->qq_callback();
        $openid = $auth->get_openid();
        $qc = new \QC($accessToken, $openid);
        $userinfo = $qc->get_user_info();
        $session = Yii::$app->session;
        $session['userinfo'] = $userinfo;
        $session['openid'] = $openid;
        if ($model = User::find()->where('openid = :openid', [':openid' => $openid])->one()) {
            $session['loginname'] = $model->username;
            $session['isLogin'] = 1;
            return $this->redirect(['index/index']);
        }
        return $this->redirect(['member/qqreg']);
    }

    public function actionQqreg()
    {
        $this->layout = "layout2";
        $model = new User;
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $session = Yii::$app->session;
            $post['User']['openid'] = $session['openid'];
            if ($model->reg($post, 'qqreg')) {
                $session['loginname'] = $post['User']['username'];
                $session['isLogin'] = 1;
                return $this->redirect(['index/index']);
            }
        }
        return $this->render('qqreg', ['model' => $model]);
    }








}

46_urlmanager/basic/views/member/auth.php
<?php
    use yii\bootstrap\ActiveForm;
    use yii\helpers\Html;
    $this->title = "登录";
?>
<!-- ============================================================= HEADER : END ============================================================= -->		<!-- ========================================= MAIN ========================================= -->
<main id="authentication" class="inner-bottom-md">
	<div class="container">
		<div class="row">
			
			<div class="col-md-6">
				<section class="section sign-in inner-right-xs">
					<h2 class="bordered">登录</h2>
					<p>欢迎您回来，请您输入您的账户名密码</p>

					<div class="social-auth-buttons">
						<div class="row">
							<div class="col-md-6">
								<button id='login_qq' class="btn-block btn-lg btn btn-facebook"><i class="fa fa-qq"></i> 使用QQ账号登录</button>
							</div>
							<div class="col-md-6">
								<button id='login_weibo' class="btn-block btn-lg btn btn-twitter"><i class="fa fa-weibo"></i> 使用新浪微博账号登录</button>
							</div>
						</div>
					</div>
                    <?php $form = ActiveForm::begin([
                        'fieldConfig' => [
                            'template' => '<div class="field-row">{label}{input}</div>{error}'
                        ],
                        'options' => [
                            'class' => 'login-form cf-style-1',
                            'role' => 'form',
                        ],
                        'action' => ['member/auth'],
                    ]); ?>
                        <?php echo $form->field($model, 'loginname')->textInput(['class' => 'le-input']); ?>
                        <?php echo $form->field($model, 'userpass')->passwordInput(['class' => 'le-input']); ?>
                        <div class="field-row clearfix">
                        <?php echo $form->field($model, 'rememberMe')->checkbox([
                            'template' => '<span class="pull-left"><label class="content-color">{input} <span class="bold">记住我</span></label></span>',
                            'class' => "le-checkbox auto-width inline",
                        ]); ?>
                        	<span class="pull-right">
                        		<a href="#" class="content-color bold">忘记密码 ?</a>
                        	</span>
                        </div>

                        <div class="buttons-holder">
                            <?php echo Html::submitButton('安全登录', ['class' => 'le-button huge']); ?>
                        </div><!-- /.buttons-holder -->

                    <?php ActiveForm::end(); ?><!-- /.cf-style-1 -->

				</section><!-- /.sign-in -->
			</div><!-- /.col -->

			<div class="col-md-6">
				<section class="section register inner-left-xs">
					<h2 class="bordered">新建账户</h2>
					<p>创建一个属于你自己的账户</p>
                    <?php
                        if (Yii::$app->session->hasFlash('info')) {
                            echo Yii::$app->session->getFlash('info');
                        }
                        $form = ActiveForm::begin([
                            'fieldConfig' => [
                                'template' => '<div class="field-row">{label}{input}</div>{error}'
                            ],
                            'options' => [
                                'class' => 'register-form cf-style-1',
                                'role' => 'form',
                            ],
                            'action' => ['member/reg'],
                        ]);
                    ?>
                        <?php echo $form->field($model, 'useremail')->textInput(['class' => 'le-input']); ?>
                        <div class="buttons-holder">
                            <?php echo Html::submitButton('注册', ['class' => 'le-button huge']); ?>
                        </div><!-- /.buttons-holder -->
                    <?php ActiveForm::end(); ?>

					<h2 class="semi-bold">加入我们您将会享受到前所未有的购物体验 :</h2>

					<ul class="list-unstyled list-benefits">
						<li><i class="fa fa-check primary-color"></i> 快捷的购物体验</li>
						<li><i class="fa fa-check primary-color"></i> 便捷的下单方式</li>
						<li><i class="fa fa-check primary-color"></i> 更加低廉的商品</li>
					</ul>

				</section><!-- /.register -->

			</div><!-- /.col -->

		</div><!-- /.row -->
	</div><!-- /.container -->
</main><!-- /.authentication -->
<!-- ========================================= MAIN : END ========================================= -->		<!-- ============================================================= FOOTER ============================================================= -->
<script>
    var qqbtn = document.getElementById("login_qq");
    qqbtn.onclick = function(){
        window.location.href="<?php echo yii\helpers\Url::to(['member/qqlogin']) ?>";
    }
</script>

46_urlmanager/basic/views/member/qqreg.php
<?php
    use yii\bootstrap\ActiveForm;
    use yii\helpers\Html;
    $this->title = "QQ登录";
?>
<!-- ============================================================= HEADER : END ============================================================= -->		<!-- ========================================= MAIN ========================================= -->
<main id="authentication" class="inner-bottom-md">
	<div class="container">
		<div class="row">
			
			<div class="col-md-6">
				<section class="section sign-in inner-right-xs">
                    <h2 class="bordered">
                        <img src="<?php echo Yii::$app->session['userinfo']['figureurl_1'] ?>">
                        完善您的信息
                    </h2>
					<p>请填写一个用户名和密码</p>

					<div class="social-auth-buttons">
					</div>
                    <?php $form = ActiveForm::begin([
                        'fieldConfig' => [
                            'template' => '<div class="field-row">{label}{input}</div>{error}'
                        ],
                        'options' => [
                            'class' => 'login-form cf-style-1',
                            'role' => 'form',
                        ],
                        //'action' => ['member/auth'],
                    ]); ?>
                        <input type="text" value="<?php echo Yii::$app->session['userinfo']['nickname'] ?>" class="le-input"><br>
                        <?php echo $form->field($model, 'username')->textInput(['class' => 'le-input']); ?>
                        <?php echo $form->field($model, 'userpass')->passwordInput(['class' => 'le-input']); ?>
                        <?php echo $form->field($model, 'repass')->passwordInput(['class' => 'le-input']); ?>
                        <div class="field-row clearfix">
                        </div>

                        <div class="buttons-holder">
                            <?php echo Html::submitButton('完善信息', ['class' => 'le-button huge']); ?>
                        </div><!-- /.buttons-holder -->

                    <?php ActiveForm::end(); ?><!-- /.cf-style-1 -->

				</section><!-- /.sign-in -->
			</div><!-- /.col -->

		</div><!-- /.row -->
	</div><!-- /.container -->
</main><!-- /.authentication -->
<!-- ========================================= MAIN : END ========================================= -->		<!-- ============================================================= FOOTER ============================================================= -->
<script>
    var qqbtn = document.getElementById("login_qq");
    qqbtn.onclick = function(){
        window.location.href="<?php echo yii\helpers\Url::to(['member/qqlogin']) ?>";
    }
</script>